### ISSUE TITLE
Game crashing in Auction House

### ISSUE THREAD

**Issue by DavidVar11** [KdGaming0/SkyBlock-Enhanced-Modpack#7]
The game crashes when browsing Auction House. Maybe my CPU and/or GPU is too slow or maybe 2 GB of Ram isn't enough?

**Comment by KdGaming0** [comment]
Is it only happening when the AH is open? Also, I would recommend upgrading the RAM to at least 3GB or 4GB if possible.

**Comment by DavidVar11** [comment]
Here is the crash log:
[crash-2024-08-07_15.55.20-client.txt](https://github.com/user-attachments/files/16531046/crash-2024-08-07_15.55.20-client.txt)
At first it happened when I opened the browsing section of AH. Then I set the GPU to the Nvidia one because I'm on a laptop. And the second time it crashed when changing filters in AH.
P.S. The attached log is the second one.

**Comment by KdGaming0** [comment]
Are you using the vanilla ah menu or the one with partly sane skies? If you are using the one with partly sane skies try to turn it of from the config menu rshift to open.

**Comment by DavidVar11** [comment]
It was the modded one. I didn't even know what mod was changing that. I've been using just NEU and Skytils before insalling this modpack. I will try to disable that menu later.

**Comment by KdGaming0** [comment]
It is most likely the modded GUI that is crashing turn it off and it should work. You will find it if you press RSHIFT and find the Partly Sane Skies mod.

**Comment by KdGaming0** [comment]
I have updated partly sane skies to version 0.6.2.-pre8 and the ah crashing is now fixed in version 1.1.4 of the modpack.
