### ISSUE TITLE
Issues with Easy Configs mod

### ISSUE THREAD

**Issue by priiimal** [KdGaming0/SkyBlock-Enhanced-Modpack#8]
Easy Configs mod has no configs in it, following your guide for the modpack exactly.

**Comment by priiimal** [comment]
so trying to load save slot 1 to use the 1440p configuration

**Comment by KdGaming0** [comment]
Have you opened the folder where the config is saved and checked if they are there? Are you trying to change from the default to the 1440p and nothing happens? Or dose something happens and the wrong configs get set.

**Comment by KdGaming0** [comment]
I forgot to include the configs when exporting the pack. I have dropped an update and they are now included. Just update and you can change to the 1440p configs.
